//
//  HelpInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HelpBusinessLogic
{
  func doSomething(request: Help.Something.Request)
}

protocol HelpDataStore
{
  //var name: String { get set }
}

class HelpInteractor: HelpBusinessLogic, HelpDataStore
{
  var presenter: HelpPresentationLogic?
  var worker: HelpWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Help.Something.Request)
  {
    worker = HelpWorker()
    worker?.doSomeWork()
    
    let response = Help.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
