//
//  EventsDetailModels.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EventsDetail
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var event: Event
    }
    struct ViewModel
    {
        struct EventDetail: Hashable {
            var name: String
            var rows = [String()]
        }
        var events: [EventDetail]
    }
  }
}
