//
//  EventsDetailPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsDetailPresentationLogic
{
  func presentSomething(response: EventsDetail.Something.Response)
}

class EventsDetailPresenter: EventsDetailPresentationLogic
{
  weak var viewController: EventsDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EventsDetail.Something.Response)
  {
    let rows = ["Info", "Schedules", "Location", "Team", "Resources", "Tasks", "Contacts"]
    // , "Attachments", "Customdata"
    
    if let header = response.event.name {
        
        let viewModel = EventsDetail.Something.ViewModel(sections: [EventsDetail.Something.ViewModel.EventDetail(header: header, rows: rows)])
        viewController?.displaySomething(viewModel: viewModel)
    } else {
        let viewModel = EventsDetail.Something.ViewModel(sections: [EventsDetail.Something.ViewModel.EventDetail(header: "", rows: rows)])
        viewController?.displaySomething(viewModel: viewModel)
    }
  }
}
