//
//  MainTabBarWorker.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 5/09/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainTabBarWorker
{
  func doSomeWork()
  {
  }
}
