//
//  MainTabBarInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 5/09/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainTabBarBusinessLogic
{
  func doSomething(request: MainTabBar.Something.Request)
}

protocol MainTabBarDataStore
{
  var basic: Yesplan { get set }
}

class MainTabBarInteractor: MainTabBarBusinessLogic, MainTabBarDataStore
{
    var basic = Yesplan()
    
  var presenter: MainTabBarPresentationLogic?
  var worker: MainTabBarWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MainTabBar.Something.Request)
  {
    worker = MainTabBarWorker()
    worker?.doSomeWork()
    
    let response = MainTabBar.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
