//
//  TasksTabRouter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TasksRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TasksDataPassing
{
  var dataStore: TasksDataStore? { get }
}

class TasksRouter: NSObject, TasksRoutingLogic, TasksDataPassing
{
  weak var viewController: TasksViewController?
  var dataStore: TasksDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
    print("Tasks Main routeToSomewhere")
      let destinationVC = TasksDetailViewController()
      var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    
  }
  // MARK: Navigation
  func navigateToSomewhere(source: TasksViewController, destination: TasksDetailViewController)
  {
    print("Tasks Main navigateToSomewhere")
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  func passDataToSomewhere(source: TasksDataStore, destination: inout TasksDetailDataStore)
  {
    print("Tasks Main passDataToSomewhere")
    let selectedItem = viewController?.v.collectionView.indexPathsForSelectedItems
    let section = selectedItem![0][0]
    let item = selectedItem![0][1]

    if let id = source.tasksDS?[section].value[item].id {
    destination.id = id
    }

  }
}
