//
//  EDInfoInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EDInfoBusinessLogic
{
  func doSomething(request: EDInfo.Something.Request)
}

protocol EDInfoDataStore
{
  //var name: String { get set }
}

class EDInfoInteractor: EDInfoBusinessLogic, EDInfoDataStore
{
  var presenter: EDInfoPresentationLogic?
  var worker: EDInfoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: EDInfo.Something.Request)
  {
    worker = EDInfoWorker()
    worker?.doSomeWork()
    
    let response = EDInfo.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
