//
//  EDInfoPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EDInfoPresentationLogic
{
  func presentSomething(response: EDInfo.Something.Response)
}

class EDInfoPresenter: EDInfoPresentationLogic
{
  weak var viewController: EDInfoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EDInfo.Something.Response)
  {
    if let name = response.event.name {
    let sections = EDInfo.Something.ViewModel(sections: [
        EDInfo.Something.ViewModel.Item(header: name, rows: [])
        ,EDInfo.Something.ViewModel.Item(header: "Info", rows: [response.event])
        ])
    let viewModel = sections
    viewController?.displaySomething(viewModel: viewModel)
    }
  }
}
