//
//  ToDosDetailRouter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ToDosDetailRoutingLogic
{
  func routeToSomewhere(row: String?)
}

protocol ToDosDetailDataPassing
{
  var dataStore: ToDosDetailDataStore? { get }
}

class ToDosDetailRouter: NSObject, ToDosDetailRoutingLogic, ToDosDetailDataPassing
{
  weak var viewController: ToDosDetailViewController?
  var dataStore: ToDosDetailDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(row: String?)
  {
    if let row = row {
        switch row {
        case "Info":
            let x = TDInfoViewController()
            let destinationVC = x
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTDInfo(source: dataStore!, destination: &destinationDS)
            navigateToTDInfo(source: viewController!, destination: destinationVC)
        case "Attachments":
            let x = TDAttachmentsViewController()
            let destinationVC = x
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTDAttachments(source: dataStore!, destination: &destinationDS)
            navigateToTDAttachments(source: viewController!, destination: destinationVC)
//        case "History":
//            let x = TDHistoryViewController()
//            let destinationVC = x
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToTDHistory(source: dataStore!, destination: &destinationDS)
//            navigateToTDHistory(source: viewController!, destination: destinationVC)
//        case "Rights":
//            let x = TDRightsViewController()
//            let destinationVC = x
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToTDRights(source: dataStore!, destination: &destinationDS)
//            navigateToTDRights(source: viewController!, destination: destinationVC)
        default:
            return
        }
    }
  }

  // MARK: Navigation
  
    func navigateToTDInfo(source: ToDosDetailViewController, destination: TDInfoViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToTDAttachments(source: ToDosDetailViewController, destination: TDAttachmentsViewController)
    {
        source.show(destination, sender: nil)
    }
    
//    func navigateToTDHistory(source: ToDosDetailViewController, destination: TDHistoryViewController)
//    {
//        source.show(destination, sender: nil)
//    }
//
//    func navigateToTDRights(source: ToDosDetailViewController, destination: TDRightsViewController)
//    {
//        source.show(destination, sender: nil)
//    }
    
//   MARK: Passing data
    
    func passDataToTDInfo(source: ToDosDetailDataStore, destination: inout TDInfoDataStore)
    {
        destination.id = source.id
    }
    
    func passDataToTDAttachments(source: ToDosDetailDataStore, destination: inout TDAttachmentsDataStore)
    {
        destination.id = source.id
    }
    
//    func passDataToTDHistory(source: ToDosDetailDataStore, destination: inout TDHistoryDataStore)
//    {
//        destination.id = source.id
//    }
//
//    func passDataToTDRights(source: ToDosDetailDataStore, destination: inout TDRightsDataStore)
//    {
//        destination.name = source.name
//        destination.id = source.id
////        print(source.id as Any)
//    }
   
}
