//
//  ToDosDetailInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDosDetailBusinessLogic
{
  func doSomething(request: ToDosDetail.Something.Request)
}

protocol ToDosDetailDataStore
{
    var id: String! { get set }
    var name: String! { get set }

}

class ToDosDetailInteractor: ToDosDetailBusinessLogic, ToDosDetailDataStore
{
      var presenter: ToDosDetailPresentationLogic?
      var worker: ToDosDetailWorker?
      var id: String!
      var name: String!

  // MARK: Do something
  
  func doSomething(request: ToDosDetail.Something.Request)
  {
    worker = ToDosDetailWorker()
    worker?.getTask(id)
        .done { result in
            self.name = result.name
            let response = ToDosDetail.Something.Response(task: result)
            self.presenter?.presentSomething(response: response)
            }
    .catch { error in
        print("error")
//              let response = ToDosTab.Something.Response(
//                  event: self.,
//                  statuses: self.statusesArray,
//                  profiles: self.profilesArray,
//                  error: error.localizedDescription
//              )
//              self.presenter?.presentToDos(response: response)
        }
//    .execute(onSuccess:
//        { event in
//            self.name = event.name
//            let response = ToDosDetail.Something.Response(event: event)
//            self.presenter?.presentSomething(response: response)
//        }, onFailure: { error in
//            print(error)
//        })
    }
}
