//
//  EventsTabModels.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EventsTab
{
  // MARK: Use cases
  
  enum Something
  {
    
    struct Request
    {
    }
    
    struct Response
    {
        var events: [(key: String, value: [Event])]
        var statuses: [Status]
        var profiles: [Profile]
        var error: String?

    }
    
    struct ViewModel
    {
        struct DisplayedEvent {
            let date: String
            let events: [Event]
        }
        
        var displayedEvents: [DisplayedEvent]
        var displayedStatuses: [String:String]
        var displayedProfiles: [String:String]
        
        var error: String?
    }    
  }
}
