//
//  EventsTabInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ws
import then

protocol EventsTabBusinessLogic
{
  func doSomething(request: EventsTab.Something.Request) // -> Promise<EventsTab.Something.Response>
//     var basic: Basic? { get set }
}

protocol EventsTabDataStore
{
//    var basic: Basic? { get set }
//    var baseKey: String? { get set }
}

class EventsTabInteractor: EventsTabBusinessLogic, EventsTabDataStore
{
    
//    var basic: Basic?
//    var baseKey: String?
  var presenter: EventsTabPresentationLogic?
  var worker: EventsTabWorker?
    
    var events: Events = Events()
    var event: Event = Event()
    var groups: Groups = Groups()
    var group: Group = Group()
    var yesplan: Yesplan = Yesplan()
  // MARK: Do something
  
  func doSomething(request: EventsTab.Something.Request) // -> Promise<EventsTab.Something.Response>
  {
    worker = EventsTabWorker()
    worker?.doSomeWork()

    
//    let me = yesplan
//    let meen = me.getAll(<#T##restResource: ArrowParsable & RestResource##ArrowParsable & RestResource#>)
//    print("me: ", me)
    
//    yesplan.ws
//    yesplan.ws = WS(UserDefaults.standard.string(forKey: "URL")!)
//    yesplan.ws = WS("https://dewerft.yesplan.be/api/events?api_key=C857C01360BB5777DABE5B7EE6594CD1")

    yesplan.getAll(events).then { events in
            self.events = events
                    }.onError { e in
                        // An error occured :/
                        print(e)
                        
                    }.finally {
            //            // In any case, reload the tableView
            //            //                print(self.events)
            //            //                print("data: ", self.events.data)
//                        for event in self.events.data {
//                            print("id: ", event.id)
//                        }
//                        let eventsMore = Events()
//                        let paginationNext = self.events.pagination.next!

//                        self.yesplan.getMore(eventsMore, paginationNext: paginationNext).then { events in
//                            print(events)
//                        }
                        
                    }

                        let response = EventsTab.Something.Response(events: self.events)
//                        print("1: ", response)
                        self.presenter?.presentSomething(response: response)
    
  }
}
