//
//  EventsTabModels.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EventsTab
{
  // MARK: Use cases
  
  enum Something
  {
    
    struct Request
    {
//        var base: Basic
//        var baseKey: String
    }
    
    struct Response
    {
        let events: Events
    }
    
    struct ViewModel
    {
//        let events: Events
//        let events: [EventViewModel]
//    }
//
//    struct EventViewModel {
//        let date: String
//        let event: Event
    }
  }
}
