//
//  EventsTabPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsTabPresentationLogic
{
  func presentSomething(response: EventsTab.Something.Response)
}

class EventsTabPresenter: EventsTabPresentationLogic
{
  weak var viewController: EventsTabDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EventsTab.Something.Response)
  {
    let viewModel = EventsTab.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
