//
//  EventsTabRouter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EventsTabRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol EventsTabDataPassing
{
  var dataStore: EventsTabDataStore? { get }
}

class EventsTabRouter: NSObject, EventsTabRoutingLogic, EventsTabDataPassing
{
  weak var viewController: EventsTabViewController?
  var dataStore: EventsTabDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
//    print("routeToSomewhere")

      let destinationVC = EventsDetailViewController()
      var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: EventsTabViewController, destination: EventsDetailViewController)
  {
//    print("navigateToSomewhere")
    
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: EventsTabDataStore, destination: inout EventsDetailDataStore)
  {
//    print("passDataToSomewhere")
    
    let selectedItem = viewController?.v.collectionView.indexPathsForSelectedItems
    let section = selectedItem![0][0]
    let item = selectedItem![0][1]

    if let id = source.eventsDS?[section].value[item].id {
    destination.id = id
    }

  }
}
