//
//  ToDoDetailPresenter.swift
//  YesplanVIP
//
//  Created by Tom Slegers on 20/02/2019.
//  Copyright (c) 2019 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoDetailPresentationLogic
{
  func presentSomething(response: ToDoDetail.Something.Response)
}

class ToDoDetailPresenter: ToDoDetailPresentationLogic
{
  weak var viewController: ToDoDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ToDoDetail.Something.Response)
  {
    let viewModel = ToDoDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
