//
//  ToDoDetailInteractor.swift
//  YesplanVIP
//
//  Created by Tom Slegers on 20/02/2019.
//  Copyright (c) 2019 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoDetailBusinessLogic
{
  func doSomething(request: ToDoDetail.Something.Request)
}

protocol ToDoDetailDataStore
{
  //var name: String { get set }
}

class ToDoDetailInteractor: ToDoDetailBusinessLogic, ToDoDetailDataStore
{
  var presenter: ToDoDetailPresentationLogic?
  var worker: ToDoDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ToDoDetail.Something.Request)
  {
    worker = ToDoDetailWorker()
    worker?.doSomeWork()
    
    let response = ToDoDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
