//
//  EDTeamWorker.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromisedFuture

class EDTeamWorker
{
    func getEventResourcebooking(_ id: String) -> Future<[Resourcebooking]> {
        return Future(operation: { completion in
            APIClient.eventResourcebookings(id)
                .map({$0})
                .execute(onSuccess: { items in
                    completion(.success(items))
                }, onFailure: { error in
                    completion(.failure(error))
                })
        })
    }
}
