//
//  EDTeamInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EDTeamBusinessLogic
{
    func doSomething(request: EDTeam.Something.Request)
}

protocol EDTeamDataStore
{
    var id: String! { get set }
    var name: String! { get set }
}

class EDTeamInteractor: EDTeamBusinessLogic, EDTeamDataStore
{
    var presenter: EDTeamPresentationLogic?
    var worker: EDTeamWorker?
    var id: String!
    var name: String!

    // MARK: Do something
    
    func doSomething(request: EDTeam.Something.Request)
    {
        worker = EDTeamWorker()
        worker?.getEventResourcebooking(id)
            .execute(onSuccess: { resourcebookings in
                let response = EDTeam.Something.Response(
                    name: self.name
                    ,resourcebookings: resourcebookings
                )
                self.presenter?.presentSomething(response: response)
            }, onFailure: { error in
                print(error)
            })
    }
}
