//
//  EDAttachmentsPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EDAttachmentsPresentationLogic
{
    func presentSomething(response: EDAttachments.Something.Response)
}

class EDAttachmentsPresenter: EDAttachmentsPresentationLogic
{
    weak var viewController: EDAttachmentsDisplayLogic?
    var sections : [EDAttachments.Something.ViewModel.Item] = []

    // MARK: Do something
    
    func presentSomething(response: EDAttachments.Something.Response)
    {
        
            let header = "Attachments"
        
        let viewModel = EDAttachments.Something.ViewModel(sections: [EDAttachments.Something.ViewModel.Item(
            header: header,
            rows: response.eventAttachments)])
        
            viewController?.displaySomething(viewModel: viewModel)
        
    }
}
