//
//  EDAttachmentsWorker.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class EDAttachmentsWorker
{
    func getEventAttachments(_ id: String) -> Promise<[EventAttachment]> {
        return firstly {
            APIClient.eventAttachments("\(id)")
            }
    }
 
}
