//
//  EDAttachmentsInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

protocol EDAttachmentsBusinessLogic
{
    func doSomething(request: EDAttachments.Something.Request)
}

protocol EDAttachmentsDataStore
{
    var id: String! { get set }
//    var name: String! { get set }
}

class EDAttachmentsInteractor: EDAttachmentsBusinessLogic, EDAttachmentsDataStore
{
    var presenter: EDAttachmentsPresentationLogic?
    var worker: EDAttachmentsWorker?
    var id: String!

    // MARK: Do something
    
    func doSomething(request: EDAttachments.Something.Request)
    {
        worker = EDAttachmentsWorker()
        worker?.getEventAttachments(id)

    .done { attachments in
            
                let response = EDAttachments.Something.Response(eventAttachments: attachments)
                self.presenter?.presentSomething(response: response)
//
            }.catch { error in
                let alert = UIAlertController(title: "Error", message: error.localizedDescription, preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "Dismiss", style: .default, handler: nil))
                //                self.present(alert, animated: true, completion: nil)
        }
    }
}
