//
//  UserTabPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserTabPresentationLogic
{
  func presentSomething(response: UserTab.Something.Response)
}

class UserTabPresenter: UserTabPresentationLogic
{
  weak var viewController: UserTabDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UserTab.Something.Response)
  {
    let viewModel = UserTab.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
