//
//  ToDosPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDosPresentationLogic
{
    func presentSomething(response: ToDosTab.Something.Response)
}

class ToDosPresenter: ToDosPresentationLogic
{
    weak var viewController: ToDosDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ToDosTab.Something.Response)
    {
        var toDos: [ToDosTab.Something.ViewModel.DisplayedToDo] = []
        
        for (key, value) in response.toDos {
            toDos.append(ToDosTab.Something.ViewModel.DisplayedToDo(date: key, toDos: value))
        }
        let viewModel = ToDosTab.Something.ViewModel(displayedToDos: toDos)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
