//
//  ToDoInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ws
import then

protocol ToDosBusinessLogic
{
    func doSomething(request: ToDosTab.Something.Request)
}

protocol ToDosDataStore
{
    //var name: String { get set }
}

class ToDosInteractor: ToDosBusinessLogic, ToDosDataStore
{
    var presenter: ToDosPresentationLogic?
    var worker: ToDosWorker?
    
//    var yesplan: Yesplan = Yesplan()
    var fetchedToDos: Tasks = Tasks()
    
    var toDosArray: [(key: String, value: [Task])] = [(key: String, value: [Task])]()
    // MARK: Do something
    
    
    func doSomething(request: ToDosTab.Something.Request)
    {
        worker = ToDosWorker()

//        yesplan.getAll(fetchedToDos, query: "task:assignedto:\(UserDefaults.standard.string(forKey: "todo_user")!) task:status:\(UserDefaults.standard.string(forKey: "todo_status")!)")
//            .then((worker?.groupToDosByDue)!)
//            .then((worker?.sortToDosInEachGroupByDue)!)
//            .then((worker?.sortDictByDate)!)
//            .then { result in
//                self.toDosArray = result
//            }
//            .onError((worker?.showErrorPopup)!)
//            
//            .finally {
//                
//                let response = ToDosTab.Something.Response(
//                    toDos: self.toDosArray
//                )
//                self.presenter?.presentSomething(response: response)
//        }
    }
}
