//
//  ToDosPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDosPresentationLogic
{
    func presentSomething(response: ToDosTab.Something.Response)
}

class ToDosPresenter: ToDosPresentationLogic
{
    weak var viewController: ToDosDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ToDosTab.Something.Response)
    {
        var toDos: [ToDosTab.Something.ViewModel.DisplayedToDo] = []
        
        for (key, value) in response.toDos {
            print(value)
            toDos.append(ToDosTab.Something.ViewModel.DisplayedToDo(date: key, toDos: value))
        }
        var viewModel = ToDosTab.Something.ViewModel(displayedToDos: toDos)
//        viewController?.displaySomething(viewModel: viewModel)
        
        if viewModel.displayedToDos.isEmpty {
            toDos.append(ToDosTab.Something.ViewModel.DisplayedToDo(date: "SUPER, All done!", toDos: [YesplanVIP.Task(
                url: URL(string: "http://")!
                , id: ""
                , owner: Optional(YesplanVIP.User(url: "https://", id: "", name: "", email: nil))
                , owningteam: Optional(YesplanVIP.Usergroup(url: "", id: "1573997569-1498158287", name: Optional("")))
                , owninggroup: Optional(YesplanVIP.Usergroup(url: "https://", id: "", name: Optional("")))
                , status: "New"
                , name: Optional("***** You've finished all your tasks! *****")
                , team: ""
                , cost: 0
                , due: "Keep up the good work!"
                , start: nil
                , description: nil
                , event: Optional(YesplanVIP.Base(url: "", id: nil, name: Optional(""), _type: nil))
                , assignedby: Optional("")
                , assignedto: Optional("")
                , duration: Optional("")
                )]))
            viewModel = ToDosTab.Something.ViewModel(displayedToDos: toDos)
        }
        
        viewController?.displaySomething(viewModel: viewModel)
    }
}
