//
//  ToDosViewController.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDosDisplayLogic: class
{
    func displaySomething(viewModel: ToDosTab.Something.ViewModel)
}

class ToDosViewController: UIViewController, UICollectionViewDelegateFlowLayout, ToDosDisplayLogic
{
    var interactor: ToDosBusinessLogic?
    var router: (NSObjectProtocol & ToDosRoutingLogic & ToDosDataPassing)?
    var v = ToDosTabView()
    var displayedToDos: [ToDosTab.Something.ViewModel.DisplayedToDo] = []
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        print("TasksViewController setup")
        
        let viewController = self
        let interactor = ToDosInteractor()
        let presenter = ToDosPresenter()
        let router = ToDosRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    //  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    //  {
    //    if let scene = segue.identifier {
    //      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
    //      if let router = router, router.responds(to: selector) {
    //        router.perform(selector, with: segue)
    //      }
    //    }
    //  }
    //
    // MARK: View lifecycle
    override func loadView() { view = v }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doSomething()
        v.refreshControl.addTarget(self, action: #selector(refresh), for: .valueChanged)
        v.collectionView.dataSource = self
    }
 
    //@IBOutlet weak var nameTextField: UITextField!
    
    @objc private func refresh() {
        print("refresh")
        doSomething()
    }
    
    func doSomething() {
        
        let request = ToDosTab.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: ToDosTab.Something.ViewModel) {
        
        displayedToDos = viewModel.displayedToDos
        self.v.collectionView.reloadData()
        self.v.refreshControl.endRefreshing()
    }
}
