//
//  ToDoModels.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ToDosTab
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
            var toDos: [(key: String, value: [Task])]
        }
        struct ViewModel
        {
            struct DisplayedToDo {
                let date: String
                let toDos: [Task]
            }
            
            var displayedToDos: [DisplayedToDo]
            var displayedStatuses: [String:String]

        }
    }
}
