//
//  EDTeamWorker.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class EDResourcesWorker
{
    func getEventResourcebookings(_ id: String) -> Promise<[Resourcebooking]> {
        return firstly {
            APIClient.eventResourcebookings("\(id)")
        }
    }
    
    func getResourcebookingId(_ id: String) -> Promise<Resourcebooking>? {
        return firstly {
            APIClient.resourcebookingId("\(id)")
        }
    }
    
    //    func getResourcesId(_ ids: [String]) -> [Promise<Resource>?] {
    //        return firstly {
    //            ids.compactMap { getResourceId($0).map{$0} }
    //        }
    //    }
    
    func getResourceId(_ id: String) -> Promise<Resource>? {
        return firstly {
            APIClient.resourceId("\(id)")
        }
    }
    
    func getLocationId(_ id: String) -> Promise<Location>? {
        return firstly {
            APIClient.locationId("\(id)")
        }
    }
}
