//
//  TDInfoInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

protocol TDInfoBusinessLogic
{
  func doSomething(request: TDInfo.Something.Request)
}

protocol TDInfoDataStore
{
  var id: String! { get set }
}

class TDInfoInteractor: TDInfoBusinessLogic, TDInfoDataStore
{
  var presenter: TDInfoPresentationLogic?
  var worker: TDInfoWorker?
    var id: String!

  // MARK: Do something
  
  func doSomething(request: TDInfo.Something.Request)
  {
    worker = TDInfoWorker()
    worker?.getTask(id)
    .done
        { task in
                let response = TDInfo.Something.Response(task: task)
                self.presenter?.presentSomething(response: response)
                
            }
  .catch { error in
    print("error")
    }
}
}
