//
//  SplashViewController.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 16/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SplashViewController: UIViewController {
    
    private let activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
    
    override func viewDidLoad() {

        super.viewDidLoad()
        
//        view.backgroundColor = UIColor.white
        
        view.addSubview(activityIndicator)
        
        activityIndicator.frame = view.bounds
        activityIndicator.backgroundColor = UIColor(white: 0, alpha: 0.4)
        
        makeServiceCall()
    }
    
    private func makeServiceCall() {

        activityIndicator.startAnimating()
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(1)) {
            self.activityIndicator.stopAnimating()
            
            if UserDefaults.standard.bool(forKey: "tasks_team_check") {
                print("tasks_team exists")
            } else {
                UserDefaults.standard.set(true, forKey: "tasks_team_check")
                UserDefaults.standard.set("*", forKey: "tasks_team")
                print("default task_team: \(UserDefaults.standard.string(forKey: "tasks_team")!)")

            }
            
            if UserDefaults.standard.bool(forKey: "todo_user_check") {
                print("todo_user exists")
            } else {
                UserDefaults.standard.set(true, forKey: "todo_user_check")
                UserDefaults.standard.set("*", forKey: "todo_user")
                print("default todo_user: \(UserDefaults.standard.string(forKey: "todo_user")!)")

            }
            
            if UserDefaults.standard.bool(forKey: "todo_status_check") {
                print("todo_status exists")
            } else {
                UserDefaults.standard.set(true, forKey: "todo_status_check")
                UserDefaults.standard.set("new", forKey: "todo_status")
                print("default todo_status: \(UserDefaults.standard.string(forKey: "todo_status")!)")
            }
            
            // Mark: Create autofillCompanyURL and autofillApiKey in Userdefaults if not existing
          
            if UserDefaults.standard.bool(forKey: "autofillCompanyURLCheck") {
                UserDefaults.standard.set(true, forKey: "autofillCompanyURLCheck")

            } else {
                let array: [String] = []
                UserDefaults.standard.set(array, forKey: "autofillCompanyURL")
                UserDefaults.standard.set(true, forKey: "autofillCompanyURLCheck")
            }
            
            if UserDefaults.standard.bool(forKey: "autofillApiKeyCheck") {
                UserDefaults.standard.set(true, forKey: "autofillApiKeyCheck")

            } else {
                let array: [String] = []
                UserDefaults.standard.set(array, forKey: "autofillApiKey")
                UserDefaults.standard.set(true, forKey: "autofillApiKeyCheck")
            }
            
//            if UserDefaults.standard.bool(forKey: "autofillUserCheck") {
//                UserDefaults.standard.set(true, forKey: "autofillUserCheck")
//
//            } else {
//                let array: [String] = []
//                UserDefaults.standard.set(array, forKey: "autofillUser")
//                UserDefaults.standard.set(true, forKey: "autofillUserCheck")
//            }
            // Mark: Check if User is Logged In
            
            if UserDefaults.standard.bool(forKey: "LOGGED_IN") {
                // Mark: if logged in, switch to main
                AppDelegate.shared.rootViewController.switchToMainScreen()
            } else {
                // Mark: if not logged in, show login
                AppDelegate.shared.rootViewController.showLoginScreen()
//                AppDelegate.shared.rootViewController.showWelcomeScreen()

            }
        }
    }
}
