//
//  SplashViewController.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 16/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SplashViewController: UIViewController {
    
    private let activityIndicator = UIActivityIndicatorView(style: .whiteLarge)
    
    override func viewDidLoad() {

        super.viewDidLoad()
        
////        view.backgroundColor = UIColor.white
//            let backgroundImageView: UIImageView = {
//                let iv = UIImageView()
//                iv.contentMode = .scaleAspectFill
////                iv.image = UIImage(named: "yesplanNB 1024x1024")
//                iv.image = #imageLiteral(resourceName: "yesplanNB 180x180.png")
//                return iv
//            }()
//        view.addSubview(backgroundImageView)
        view.addSubview(activityIndicator)
        
        activityIndicator.frame = view.bounds
        activityIndicator.backgroundColor = UIColor(white: 0, alpha: 0.4)
        
        makeServiceCall()
    }
    
    private func makeServiceCall() {

        activityIndicator.startAnimating()
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(1)) {
            self.activityIndicator.stopAnimating()
            
            // Mark: Create autofillCompanyURL and autofillApiKey in Userdefaults if not existing
          
            if UserDefaults.standard.bool(forKey: "autofillCompanyURLCheck") {
                UserDefaults.standard.set(true, forKey: "autofillCompanyURLCheck")

            } else {
                let array: [String] = []
                UserDefaults.standard.set(array, forKey: "autofillCompanyURL")
                UserDefaults.standard.set(true, forKey: "autofillCompanyURLCheck")
            }
            
            if UserDefaults.standard.bool(forKey: "autofillApiKeyCheck") {
                UserDefaults.standard.set(true, forKey: "autofillApiKeyCheck")

            } else {
                let array: [String] = []
                UserDefaults.standard.set(array, forKey: "autofillApiKey")
                UserDefaults.standard.set(true, forKey: "autofillApiKeyCheck")
            }
        
            // Mark: Check if User is Logged In
            
            if UserDefaults.standard.bool(forKey: "LOGGED_IN") {
                // Mark: if logged in, switch to main
                AppDelegate.shared.rootViewController.switchToMainScreen()
            } else {
                // Mark: if not logged in, show login
                AppDelegate.shared.rootViewController.showLoginScreen()
//                AppDelegate.shared.rootViewController.showWelcomeScreen()

            }
        }
    }
}
