//
//  TasksPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TasksPresentationLogic
{
  func presentSomething(response: TasksTab.Something.Response)
}

class TasksPresenter: TasksPresentationLogic
{
  weak var viewController: TasksDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TasksTab.Something.Response)
  {
    var tasks: [TasksTab.Something.ViewModel.DisplayedTask] = []
    
    if response.error != nil { let viewModel = TasksTab.Something.ViewModel(
        displayedTasks: tasks,
        error: response.error!
        )
        viewController?.displaySomething(viewModel: viewModel)
    }
    else {
    for (key, value) in response.tasks {
        tasks.append(TasksTab.Something.ViewModel.DisplayedTask(date: key, tasks: value))
    }
    let viewModel = TasksTab.Something.ViewModel(
        displayedTasks: tasks,
        error: nil
        )
    viewController?.displaySomething(viewModel: viewModel)
    }
  }
}
