//
//  TasksPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TasksPresentationLogic
{
  func presentSomething(response: TasksTab.Something.Response)
}

class TasksPresenter: TasksPresentationLogic
{
  weak var viewController: TasksDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TasksTab.Something.Response)
  {
//    print("TasksPresenter")
    var tasks: [TasksTab.Something.ViewModel.DisplayedTask] = []
    var statusesDict: [String:String] = [:]
    
    
    if response.error != nil {
//        print(response.error!)
        let viewModel = TasksTab.Something.ViewModel(
        displayedTasks: tasks
        ,displayedStatuses: statusesDict
        ,error: response.error!
        )
        viewController?.displaySomething(viewModel: viewModel)
    } else {
        for (key, value) in response.tasks {
            tasks.append(TasksTab.Something.ViewModel.DisplayedTask(date: key, tasks: value))
    }
        statusesDict = ["New": "rgb(255,200,200)", "Started": "rgb(255,230,200)", "Done": "rgb(230,255,200)", "On hold": "rgb(100,100,200)", "Obsolete": "rgb(165,100,200)"]
        
    let viewModel = TasksTab.Something.ViewModel(
        displayedTasks: tasks
        ,displayedStatuses: statusesDict
        ,error: nil
        )
    viewController?.displaySomething(viewModel: viewModel)
        
        
    }
  }
}
