//
//  LoginModels.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 14/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

enum Login
{
  // MARK: Use cases
  
  enum EnterLogin
  {
    struct Request
    {
        var companyURL: String?
        var apiKey: String?
    }
    struct Response
    {
        var success: Bool
        var error: String?
    }
    struct ViewModel
    {
        var success: Bool
        var error: String?
    }
  }
}
