//
//  LoginViewController.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 14/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
//import Firebase

protocol LoginDisplayLogic: class
{
  func displaySomething(viewModel: Login.EnterLogin.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
  var interactor: LoginBusinessLogic?
  var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
 
    var loginView: LoginView!
    let defaults = UserDefaults.standard
//    var favouritessetCompanyURL = UserDefaults.standard.bool(forKey: "autofillCompanyURL")
  
    var autofillCompanyURL: [String] = UserDefaults.standard.array(forKey: "autofillCompanyURL") as! [String]

//    var favouritessetApiKey = UserDefaults.standard.bool(forKey: "autofillCompanyURL")

    var autofillApiKey: [String] = UserDefaults.standard.array(forKey: "autofillApiKey") as! [String]



  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    print("override init nib")
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
//
  required init?(coder aDecoder: NSCoder)
  {
    print("required init coder")

    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    print("LoginViewController setup")
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
    print("LoginViewController setup finished")

  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    print("LoginViewController viewDidLoad")

    super.viewDidLoad()
    title = NSLocalizedString("Login", comment: String(describing: LoginViewController.self))
    setupView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        print("LoginViewController viewWillAppear")

        super.viewWillAppear(animated)
        navigationController?.navigationBar.isHidden = true
    }
    
    func setupView() {
        print("LoginViewController setupView")
        let mainView = LoginView(frame: self.view.frame)
        self.loginView = mainView
        self.loginView.loginAction = login
//        self.loginView.signupAction = signupPressed
        self.view.addSubview(loginView)
        loginView.setAnchor(top: view.topAnchor, left: view.leftAnchor, bottom: view.bottomAnchor, right: view.rightAnchor, paddingTop: 0, paddingLeft: 0, paddingBottom: 0, paddingRight: 0)
    }
  
    
    func signupPressed() {
        // 1
        print("LoginViewController signupPressed")
//        let signUpVC = SignUpController()
//        present(signUpVC, animated: true, completion: nil)
    }
    

  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func login()
  {
    print("LoginViewController login")

    let companyUrl = loginView.companyURLTextField.text
    let apiKey = loginView.apiKeyTextField.text
    let request = Login.EnterLogin.Request(companyURL: companyUrl, apiKey: apiKey)
    interactor?.loginPressed(request: request)
    
  }
  
  func displaySomething(viewModel: Login.EnterLogin.ViewModel)
  {
    print("LoginViewController displaySomething")

    if viewModel.success {
        
        self.defaults.set(true, forKey: "LOGGED_IN")
        
        autofillCompanyURL.append(loginView.companyURLTextField.text!)
        autofillCompanyURL = Array(Set(autofillCompanyURL))
        self.defaults.set(autofillCompanyURL, forKey: "autofillCompanyURL" )

        autofillApiKey.append(loginView.apiKeyTextField.text!)
        autofillApiKey = Array(Set(autofillApiKey))
        self.defaults.set(autofillApiKey, forKey: "autofillApiKey" )

        AppDelegate.shared.rootViewController.switchToMainScreen()
        
    } else {
        print("back to the beginning")
//        loginView.companyURLTextField.text = nil
        loginView.apiKeyTextField.text = nil
        
    }
  }
}
