//
//  LoginWorker.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 14/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import then
import ws
import Arrow

class LoginWorker
{
    var ikke: Bool = Bool()

    func verifyUrl(urlString: String?) -> Promise<Bool> {
    return Promise { resolve, reject in
//        print("Testing URL ...")
    Alamofire.request(urlString!)
        .validate()
        .responseJSON { response in
            
            switch response.result {
            case .success(let data):
                resolve(true)
                
            case .failure(let error):
                print(error)
                resolve(false)
            }
            }
        }
    }
}
