//
//  LoginRouter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 14/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

 protocol LoginRoutingLogic
{
  func routeToSomewhere()
}

 protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
    func routeToSomewhere() {
        print("LoginRouter.routeToSomewhere")
         let destinationVC = EventsTabViewController()
        var destinationDS = destinationVC.router!.dataStore!
         passDataToSomewhere(source: dataStore!, destination: &destinationDS)
         navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
     // MARK: - Navigation
     func navigateToSomewhere(source: LoginViewController, destination: EventsTabViewController) {
       source.show(destination, sender: nil)
     }
     // MARK: - Passing data
     func passDataToSomewhere(source: LoginDataStore, destination: inout EventsTabDataStore) {
       destination.basic = source.basic
     }
}
//  func passDataToMainTabBar(source: LoginDataStore, destination: inout EventsTabDataStore)
//  {
//    destination.basic = source.basic
//    print("source.basic: ", source.basic)
//    print("destination.basic: ", destination.basic)
//
//  }

    
//}
