//
//  EventsDetailRouter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EventsDetailRoutingLogic
{
  func routeToSomewhere(row: String?)
}

protocol EventsDetailDataPassing
{
  var dataStore: EventsDetailDataStore? { get }
}

class EventsDetailRouter: NSObject, EventsDetailRoutingLogic, EventsDetailDataPassing
{
  weak var viewController: EventsDetailViewController?
  var dataStore: EventsDetailDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(row: String?)
  {
    if let row = row {
        switch row {
        case "Info":
            let x = EDInfoViewController()
            let destinationVC = x
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEDInfo(source: dataStore!, destination: &destinationDS)
            navigateToEDInfo(source: viewController!, destination: destinationVC)
        case "Schedules":
            let x = EDSchedulesViewController()
            let destinationVC = x
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEDSchedules(source: dataStore!, destination: &destinationDS)
            navigateToEDSchedules(source: viewController!, destination: destinationVC)
        case "Location":
            let x = EDLocationViewController()
            let destinationVC = x
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEDLocation(source: dataStore!, destination: &destinationDS)
            navigateToEDLocation(source: viewController!, destination: destinationVC)
        case "Team":
            let x = EDTeamViewController()
            let destinationVC = x
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEDTeam(source: dataStore!, destination: &destinationDS)
            navigateToEDTeam(source: viewController!, destination: destinationVC)
        default:
            return
        }
    }
  }

  // MARK: Navigation
  
    func navigateToEDInfo(source: EventsDetailViewController, destination: EDInfoViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToEDSchedules(source: EventsDetailViewController, destination: EDSchedulesViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToEDLocation(source: EventsDetailViewController, destination: EDLocationViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToEDTeam(source: EventsDetailViewController, destination: EDTeamViewController)
    {
        source.show(destination, sender: nil)
    }
    
//   MARK: Passing data
    
    func passDataToEDInfo(source: EventsDetailDataStore, destination: inout EDInfoDataStore)
    {
        destination.id = source.id
    }
    
    func passDataToEDSchedules(source: EventsDetailDataStore, destination: inout EDSchedulesDataStore)
    {
        destination.id = source.id
    }
    
    func passDataToEDLocation(source: EventsDetailDataStore, destination: inout EDLocationDataStore)
    {
        destination.id = source.id
    }
    
    func passDataToEDTeam(source: EventsDetailDataStore, destination: inout EDTeamDataStore)
    {
        destination.name = source.name
        destination.id = source.id
        print(source.id as Any)
    }
}
