//
//  EventsInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsBusinessLogic
{
  func doSomething(request: Events.Something.Request)
}

protocol EventsDataStore
{
  //var name: String { get set }
}

class EventsInteractor: EventsBusinessLogic, EventsDataStore
{
  var presenter: EventsPresentationLogic?
  var worker: EventsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Events.Something.Request)
  {
    worker = EventsWorker()
    worker?.doSomeWork()
    
    let response = Events.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
