//
//  EDSchedulesPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EDSchedulesPresentationLogic
{
  func presentSomething(response: EDSchedules.Something.Response)
}

class EDSchedulesPresenter: EDSchedulesPresentationLogic
{
  weak var viewController: EDSchedulesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EDSchedules.Something.Response)
  {
    if let name = response.eventSchedule.event.name {
        let name = name
        let rows = response.eventSchedule
        let sections = EDSchedules.Something.ViewModel(sections:
        [
            EDSchedules.Something.ViewModel.Item(header: name, rows: nil),
            EDSchedules.Something.ViewModel.Item(header: "Schedules", rows: rows),
        ]
        )
        let viewModel = sections
        viewController?.displaySomething(viewModel: viewModel)
    }
  }
}
