//
//  EDLocationPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EDLocationPresentationLogic
{
    func presentSomething(response: EDLocation.Something.Response)
}

class EDLocationPresenter: EDLocationPresentationLogic
{
    weak var viewController: EDLocationDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: EDLocation.Something.Response)
    {
//        print("present: ", response)
        if let name = response.event.name {
            let name = name
            let rows = response.event
            let sections = EDLocation.Something.ViewModel(sections: [EDLocation.Something.ViewModel.Item(header: "Locations - \(name)", rows: [rows])])
            let viewModel = sections
            viewController?.displaySomething(viewModel: viewModel)
        } else {
            let rows = response.event
            let sections = EDLocation.Something.ViewModel(sections: [EDLocation.Something.ViewModel.Item(header: "Locations", rows: [rows])])
            let viewModel = sections
            viewController?.displaySomething(viewModel: viewModel)
        }
        
    }
}
