//
//  EDLocationInteractor.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 11/11/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EDLocationBusinessLogic
{
    func doSomething(request: EDLocation.Something.Request)
}

protocol EDLocationDataStore
{
    var id: String! { get set }
}

class EDLocationInteractor: EDLocationBusinessLogic, EDLocationDataStore
{
    var presenter: EDLocationPresentationLogic?
    var worker: EDLocationWorker?
    var id: String!
    
    // MARK: Do something
    
    func doSomething(request: EDLocation.Something.Request)
    {
        worker = EDLocationWorker()
        worker?.getEvent(id)
            .done { result in
                let response = EDLocation.Something.Response(event: result)
                self.presenter?.presentSomething(response: response)
        }
        .catch { error in
            print("error")
        }
    }
}
