//
//  EventsTabViewController.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 22/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit
import SwiftUI
import MDatePickerView

protocol EventsTabDisplayLogic: class
{
  func displaySomething(viewModel: EventsTab.Something.ViewModel)
}

class EventsTabViewController: UIViewController, UICollectionViewDelegateFlowLayout, EventsTabDisplayLogic
{
     lazy var MDate : MDatePickerView = {
        let mdate = MDatePickerView()
            mdate.delegate = self
        mdate.Color = UIColor.darkGray
        mdate.translatesAutoresizingMaskIntoConstraints = false
        return mdate
       }()
    
    private var embedController: EmbedController?
    
    let Today : UIButton = {
        let but = UIButton(type:.system)
        but.tintColor = UIColor.white
        but.setTitle("ToDay", for: .normal)
        but.addTarget(self, action: #selector(today), for: .touchUpInside)
        but.translatesAutoresizingMaskIntoConstraints = false
        return but
    }()
    
    @objc func today() {
        MDate.selectDate = Date()
    }
    
    // *************
    
    @IBOutlet weak var calendarView: CalendarView!
    @IBOutlet weak var caldatePicker: UIDatePicker!
       
    
    // **************
    
    var datePicker : UIDatePicker = UIDatePicker()
    var toolBar = UIToolbar()

    var interactor: EventsTabBusinessLogic?
    var router: (NSObjectProtocol & EventsTabRoutingLogic & EventsTabDataPassing)?
    var v = EventsTabView()
//    var calView = CalendarView()
    var displayedEvents: [EventsTab.Something.ViewModel.DisplayedEvent] = []
    var displayedStatuses: [String:String] = [:]
    var displayedProfiles: [String:String] = [:]

    
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {

    let viewController = self
    let interactor = EventsTabInteractor()
    let presenter = EventsTabPresenter()
    let router = EventsTabRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
//  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
//  {
//    if let scene = segue.identifier {
//      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
//      if let router = router, router.responds(to: selector) {
//        router.perform(selector, with: segue)
//      }
//    }
//  }
  
  // MARK: View lifecycle
    
    override func loadView() { view = v }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        //Swipe Gestures
        let leftSwipe = UISwipeGestureRecognizer(target: self, action: #selector(handleSwipes(_:)))
        let rightSwipe = UISwipeGestureRecognizer(target: self, action: #selector(handleSwipes(_:)))
            
        leftSwipe.direction = .left
        rightSwipe.direction = .right

        self.view.addGestureRecognizer(leftSwipe)
        self.view.addGestureRecognizer(rightSwipe)
        
        // NavigationBarButtons:
        // Yesplan Prefs Button
        let yesplanPrefsButton = UIButton(type: .system)
        yesplanPrefsButton.addTarget(self, action: #selector(yesplanPrefs), for: .touchUpInside)
        yesplanPrefsButton.setImage(#imageLiteral(resourceName: "yesplanNB 180x180"), for: .normal)
        yesplanPrefsButton.setTitle("setup", for: .normal)
        yesplanPrefsButton.tintColor = UIColor.yellow
        let widthConstraintYesplanPrefsButton = yesplanPrefsButton.widthAnchor.constraint(equalToConstant: 32)
        let heightConstraintYesplanPrefsButton = yesplanPrefsButton.heightAnchor.constraint(equalToConstant: 32)
        heightConstraintYesplanPrefsButton.isActive = true
        widthConstraintYesplanPrefsButton.isActive = true
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(customView: yesplanPrefsButton)
        
        // calendarLeftButton
        let calendarLeftButton = UIButton(type: .system)
        calendarLeftButton.addTarget(self, action: #selector(calendarLeft), for: .touchUpInside)
        calendarLeftButton.setImage(#imageLiteral(resourceName: "CalendarLeft.png"), for: .normal)
        calendarLeftButton.setTitle("", for: .normal)
        calendarLeftButton.tintColor = UIColor.gray
        let widthConstraintCalendarLeftButton = calendarLeftButton.widthAnchor.constraint(equalToConstant: 20)
        let heightConstraintCalendarLeftButton = calendarLeftButton.heightAnchor.constraint(equalToConstant: 20)
        heightConstraintCalendarLeftButton.isActive = true
        widthConstraintCalendarLeftButton.isActive = true
        let leftbarButtonItem1 = UIBarButtonItem(customView: calendarLeftButton)
        
        // CalendarButton
        let calendarButton = UIButton(type: .system)
        calendarButton.addTarget(self, action: #selector(calendar), for: .touchUpInside)
        calendarButton.setImage(#imageLiteral(resourceName: "Calendar"), for: .normal)
        calendarButton.setTitle("", for: .normal)
        calendarButton.tintColor = UIColor.gray
        let widthConstraintCalendarButton = calendarButton.widthAnchor.constraint(equalToConstant: 20)
        let heightConstraintCalendarButton = calendarButton.heightAnchor.constraint(equalToConstant: 20)
        heightConstraintCalendarButton.isActive = true
        widthConstraintCalendarButton.isActive = true
        let leftbarButtonItem2 = UIBarButtonItem(customView: calendarButton)
        
        // CalendarRightButton
        let calendarRightButton = UIButton(type: .system)
        calendarRightButton.addTarget(self, action: #selector(calendarRight), for: .touchUpInside)
        calendarRightButton.setImage(#imageLiteral(resourceName: "CalendarRight"), for: .normal)
        calendarRightButton.setTitle("", for: .normal)
        calendarRightButton.tintColor = UIColor.gray
        let widthConstraintCalendarRightButton = calendarRightButton.widthAnchor.constraint(equalToConstant: 20)
        let heightConstraintCalendarRightButton = calendarRightButton.heightAnchor.constraint(equalToConstant: 20)
        heightConstraintCalendarRightButton.isActive = true
        widthConstraintCalendarRightButton.isActive = true
        let leftbarButtonItem3 = UIBarButtonItem(customView: calendarRightButton)

        
        self.navigationItem.leftBarButtonItems = [leftbarButtonItem1, leftbarButtonItem2, leftbarButtonItem3]
        
        self.title = "Events"
        
    NotificationCenter.default.addObserver(self, selector: #selector(userDefaultsDidChange), name: UserDefaults.didChangeNotification, object: nil)
        
  }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        NotificationCenter.default.addObserver(self, selector: #selector(userDefaultsDidChange), name: UserDefaults.didChangeNotification, object: nil)
        doSomething()
        
        v.refreshControl.addTarget(self, action: #selector(refresh), for: .valueChanged)
//        if #available(iOS 10.0, *) {
//            v.collectionView.prefetchDataSource = self
//        }
        v.collectionView.dataSource = self
        v.collectionView.delegate = self
//        v.collectionView.prefetchDataSource = self
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        NotificationCenter.default.removeObserver(self)
    }
    
    @objc func handleSwipes(_ sender:UISwipeGestureRecognizer) {
            
        if (sender.direction == .left) {
            calendarDayPlus()
        }
            
        if (sender.direction == .right) {
            calendarDayMinus()
        }
    }
    @objc func userDefaultsDidChange(){
        doSomething()
    }
    
    @objc func calendar() {
        
        
//        if #available(iOS 13.0, *) {
//            let calendarView = ContentView()
//            
//            let host = UIHostingController(rootView: calendarView)
//            navigationController?.pushViewController(host, animated: true)
//            
//        } else {
            
        
//            embedController = EmbedController(rootViewController: self)
//
//               let newViewController = CalViewController()
//        newViewController.view.frame = CGRect(x: 0, y: 85, width: self.view.frame.width, height: self.view.frame.height)
//
//               newViewController.view.backgroundColor = .lightGray
//               embedController?.append(viewController: newViewController)
           
        
        
        toolBar = UIToolbar(frame: CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: self.view.frame.size.height - (self.tabBarController?.tabBar.frame.height)!))

        toolBar.barTintColor = UIColor.black
        toolBar.tintColor = UIColor.white
        toolBar.barStyle = UIBarStyle.blackTranslucent
        toolBar.isTranslucent = true
        toolBar.isUserInteractionEnabled = true

        let cancelButton = UIBarButtonItem(title: "Cancel", style: .plain, target: self, action: #selector(cancelDatePicker));
        let spaceButton = UIBarButtonItem(barButtonSystemItem: UIBarButtonItem.SystemItem.flexibleSpace, target: nil, action: nil)
        let doneButton = UIBarButtonItem(title: "Done", style: .done, target: self, action: #selector(donedatePicker));
        toolBar.setItems([doneButton,spaceButton,cancelButton], animated: false)

        self.view.addSubview(toolBar)
        self.view.addSubview(MDate)
               NSLayoutConstraint.activate([
                   MDate.centerYAnchor.constraint(equalTo: view.centerYAnchor, constant: 0),
                   MDate.centerXAnchor.constraint(equalTo: view.centerXAnchor, constant: 0),
                   MDate.widthAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.7),
                   MDate.heightAnchor.constraint(equalTo: view.heightAnchor, multiplier: 0.4)
               ])
        self.view.addSubview(Today)
               Today.centerXAnchor.constraint(equalTo: view.centerXAnchor, constant: 0).isActive = true
               Today.topAnchor.constraint(equalTo: MDate.bottomAnchor, constant: 20).isActive = true
//        }
    }
    
    @objc func yesplanPrefs(sender: AnyObject) {
        if let url = URL(string:UIApplication.openSettingsURLString) {
            if UIApplication.shared.canOpenURL(url) {
                _ =  UIApplication.shared.open(url, options: [:], completionHandler: nil)
            }
        }
    }
//    @State private var wakeUp = Date() // Only from iOS13.0
    // Datepicker:
    
    @objc func calendarLeft(sender: AnyObject) {
        calendarDayMinus()
    }
    
    func calendarDayMinus() {
        
        datePicker.date = Calendar.current.date(byAdding: .day, value: -1, to: datePicker.date)!
        doSomething()
//        self.datePicker.removeFromSuperview()
        self.MDate.removeFromSuperview()
        self.toolBar.removeFromSuperview()
    }
    
    @objc func calendarRight(sender: AnyObject) {
        calendarDayPlus()
    }
    
    func calendarDayPlus() {
        
        datePicker.date = Calendar.current.date(byAdding: .day, value: 1, to: datePicker.date)!
        doSomething()
        self.datePicker.removeFromSuperview()
//        self.datePicker.removeFromSuperview()
        self.MDate.removeFromSuperview()
        self.toolBar.removeFromSuperview()
    }
    
//    @objc func pick(sender: AnyObject) {
//
//        datePicker = UIDatePicker(frame: CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: self.view.frame.size.height - 95)) // self.view.frame.size.height))
//        datePicker.datePickerMode = UIDatePicker.Mode.date
//        datePicker.setValue(UIColor.lightGray, forKeyPath: "textColor")
//        datePicker.backgroundColor = UIColor.black
//
//        toolBar = UIToolbar(frame: CGRect(x: 0, y: 0
//            , width: self.view.frame.size.width, height: self.view.frame.size.height - 48))
//
//        toolBar.barTintColor = UIColor.darkGray
//        toolBar.tintColor = UIColor.lightGray
//        toolBar.barStyle = UIBarStyle.blackTranslucent
//        toolBar.isTranslucent = true
//        toolBar.isUserInteractionEnabled = true
//
//        let cancelButton = UIBarButtonItem(title: "Cancel", style: .plain, target: self, action: #selector(cancelDatePicker));
//        let spaceButton = UIBarButtonItem(barButtonSystemItem: UIBarButtonItem.SystemItem.flexibleSpace, target: nil, action: nil)
//         let doneButton = UIBarButtonItem(title: "Done", style: .done, target: self, action: #selector(donedatePicker));
//        toolBar.setItems([doneButton,spaceButton,cancelButton], animated: false)
//
//        self.view.addSubview(toolBar)
//        self.view.addSubview(datePicker)
//        }

         @objc func donedatePicker(){

            doSomething()
            self.MDate.removeFromSuperview()
//            self.datePicker.removeFromSuperview()
            self.toolBar.removeFromSuperview()
//            self.view.endEditing(true)

        }
//
        @objc func cancelDatePicker(){
//            print("canceled")
//            self.datePicker.removeFromSuperview()
            self.MDate.removeFromSuperview()
            self.toolBar.removeFromSuperview()

//           self.view.endEditing(true)
         }
//
//           func dueDateChanged(sender:UIDatePicker){
//               var dateFormatter = DateFormatter()
//            print("date:", dateFormatter)
////            dateFormatter.dateStyle = DateFormatter.Style.LongStyle
////            dateFormatter.timeStyle = DateFormatter.Style.NoStyle
////               self.myLabel.text = dateFormatter.stringFromDate(dueDatePickerView.date)
//           }
    
    @objc private func refresh() {
        doSomething()
    }
    
    // MARK: Do something


    
  func doSomething() {
    
    let formatter = DateFormatter()
    formatter.dateFormat = "dd-MM-yyyy"
    
    let request = EventsTab.Something.Request(
        startdate: "\(formatter.string(from: datePicker.date))",
        enddate: "\(formatter.string(from: Calendar.current.date(byAdding: .day, value: 0, to: datePicker.date)!))"
    )
    interactor?.doSomething(request: request)
  }
  
    
  func displaySomething(viewModel: EventsTab.Something.ViewModel ) {
    displayedEvents = viewModel.displayedEvents
    displayedProfiles = viewModel.displayedProfiles
    displayedStatuses = viewModel.displayedStatuses
    
    if viewModel.error != nil {
    let alert = UIAlertController(title: "Alert", message: "\(viewModel.error!)", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Cancel", style: .default, handler: nil))
        alert.addAction(UIAlertAction(title: "Retry", style: .cancel, handler: { action in
            self.doSomething()
        }))
    self.present(alert, animated: true)
    }
    
    self.v.collectionView.reloadData()
    self.v.refreshControl.endRefreshing()
  }
}

