//
//  TeamplannerModels.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
//import PromisedFuture

enum TeamplannerTab
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var startdate: String
        var enddate: String
    }
    struct Response
    {
//        struct Row: Codable {
//            let schedules: Schedules?
//            let resourcebooking: Schedules? // Resourcebooking?
//        }
//        var header: String?
//        var rows: [Row]

        var resourcebookings: [Resourcebooking]?
        var schedules: [[String? : [Schedules]]]
        var error: String?
    }
    
//    struct ResourcebookingsResponse {
//        var Resourcebookings: [Resourcebooking]
//    }
    
    struct ViewModel
    {
        struct Section: Codable {
            var header: String?
            struct Row: Codable {
                let schedules: Schedules?
                let resourcebooking: Resourcebooking?
            }
            let rows: [Row]
        }
//
//        struct Displ: Hashable {
//
//            let date: String
//            let scheduleType: String
//            let start: String
//            let end: String
//            let eventName: String?
//        }

//        var sections: Set<Item>
        var sections: [Section]
        var error: String?

    }
  }
}
