//
//  TeamplannerModels.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromisedFuture

enum TeamplannerTab
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
//        var resourcebookings: [Resourcebooking]
        var resourceSchedules: [ResourceScheduleFromTo]
        var error: String?
    }
    struct ViewModel
    {
        struct DisplayedResourcebooking: Hashable {
            let date: String
            let resourcebookings: [Displ]
        }

        struct Displ: Hashable {
            
            let date: String
            let scheduleType: String
            let start: String
            let end: String
            let eventName: String?
//            let role: String
        }

//        var displayedResourcebookings: Set<DisplayedResourcebooking>
        var toVC: Set<Displ>
        var error: String?

    }
  }
}
