//
//  UserPresenter.swift
//  YesplanVIP
//
//  Created by Techcc - FOH - Video on 13/08/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserPresentationLogic
{
  func presentSomething(response: User.Something.Response)
}

class UserPresenter: UserPresentationLogic
{
  weak var viewController: UserDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: User.Something.Response)
  {
    let viewModel = User.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
